/**
 * 
 */
package com.universalstudios.orlandoresort.controller.userinterface.explore;

/**
 * 
 * 
 * @author Steven Byle
 */
public enum ExploreType {
	ISLANDS_OF_ADVENTURE(1),
	UNIVERSAL_STUDIOS_FLORIDA(2),
	CITY_WALK_ORLANDO(3),
	RIDES(4),
	SHOWS(5),
	DINING(6),
	SHOPPING(7),
	RESTROOMS(8),
	LOCKERS(9),
	GUEST_SERVICES_BOOTHS(10),
	ATMS(11),
	CHARGING_STATIONS(12),
	LOST_AND_FOUND(13),
	FIRST_AID(14),
	SERVICE_ANIMAL_REST_AREAS(15),
	SMOKING_AREAS(16),
	HOTELS(17),
	SOLO_MAP_PAGE(18),
	DETAIL_PAGE_MAP_SNAPSHOT(19),
	SHOPPING_EXPRESS_PASS(20),
	HOME_PAGE_MAP_SNAPSHOT(21),
	FAVORITES(22),
	WAIT_TIMES(23),
	ATTRACTIONS_EXPRESS_PASS(24),
	WET_N_WILD(25),
	EVENTS(26),
	ATTRACTIONS(27),
	EVENT_MAP(28),
	EVENT_LIST(29),
	UPCOMING_EVENTS(30),
	OFFERS(31),
	OFFER_SERIES(32),
	UNIVERSAL_DINING(33),
	UNIVERSAL_DINING_QUICK_SERVICE(34),
	ATTRACTIONS_PACKAGE_PICKUP(35),
	EVENT_SERIES_ATTRACTIONS(36),
	GATEWAYS(37),
	GENERAL_LOCATIONS(38),
	EVENT_SERIES_EVENTS(39),
	RENTAL_SERVICES(40),
	UNIVERSAL_STUDIOS_HOLLYWOOD_ATTRACTIONS(41),
	UNIVERSAL_STUDIOS_HOLLYWOOD_DINING(42),
	UNIVERSAL_STUDIOS_HOLLYWOOD_SHOPPING(43),
	CITY_WALK_HOLLYWOOD(44),
	VOLCANO_BAY(45);

	private final int value;
	private ExploreType(int value) {
		this.value = value;
	}

	public int getValue() {
		return value;
	}
}
